name: Message updating

on: workflow_dispatch
    # schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    #     - cron: '0 11 * * 1-5'
    
jobs:
  set-up:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: script run
        run: node ./run-script.js
          
