name: Message updating
on: workflow_dispatch
    # schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    #     - cron: '0 11 * * 1-5'
    
jobs:
  set-up:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: script run
        run: node ./run-script.js
#       - name: git commit
#         run: |
#           git add src/message.txt
#           git commit -m "new commit"
#           git push origin master
      - name: Check code differences
        uses: technote-space/get-diff-action@v6
        with: 
          PATTERNS: 'src/**'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update messages
          title: Update MESSAGES
          body: Credit new contributors by updating MESSAGES
          branch: update-messages
        if: env.GIT_DIFF
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: '.'

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
      
